### ISSUE TITLE
error

### ISSUE THREAD

**Issue by julio-cotta-edx** [kissmetrics/KISSmetrics-Android-SDK#11]
Got it while initializing the lib
```java
java.lang.NoSuchMethodError: fli
       at java.lang.Class.getConstructorOrMethod(Class.java:460)
       at java.lang.Class.getDeclaredMethod(Class.java:685)
       at java.io.ObjectStreamClass.findMethod(ObjectStreamClass.java:1111)
       at java.io.ObjectStreamClass.createClassDesc(ObjectStreamClass.java:299)
       at java.io.ObjectStreamClass.lookupStreamClass(ObjectStreamClass.java:1069)
       at java.io.ObjectStreamClass.lookup(ObjectStreamClass.java:1037)
       at java.io.ObjectStreamClass.createClassDesc(ObjectStreamClass.java:248)
       at java.io.ObjectStreamClass.lookupStreamClass(ObjectStreamClass.java:1069)
       at java.io.ObjectStreamClass.lookup(ObjectStreamClass.java:1037)
       at java.io.ObjectStreamClass.createClassDesc(ObjectStreamClass.java:248)
       at java.io.ObjectStreamClass.lookupStreamClass(ObjectStreamClass.java:1069)
       at java.io.ObjectInputStream.verifyAndInit(ObjectInputStream.java:2371)
       at java.io.ObjectInputStream.readNewClassDesc(ObjectInputStream.java:1658)
       at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:683)
       at java.io.ObjectInputStream.readNewObject(ObjectInputStream.java:1799)
       at java.io.ObjectInputStream.readNonPrimitiveContent(ObjectInputStream.java:787)
       at java.io.ObjectInputStream.readObject(ObjectInputStream.java:1999)
       at java.io.ObjectInputStream.readObject(ObjectInputStream.java:1956)
       at com.kissmetrics.sdk.ArchiverImpl.unarchiveSettings(ArchiverImpl.java:146)
       at com.kissmetrics.sdk.ArchiverImpl.<init>(ArchiverImpl.java:88)
       at com.kissmetrics.sdk.ArchiverImpl.sharedArchiver(ArchiverImpl.java:108)
       at com.kissmetrics.sdk.KISSmetricsAPI.<init>(KISSmetricsAPI.java:91)
       at com.kissmetrics.sdk.KISSmetricsAPI.sharedAPI(KISSmetricsAPI.java:137)
```

**Comment by healyk** [comment]
This issue looks to be resolved.  If it isn't please reopen the issue with any new details you have.
