### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by BugsBunnyBR** [kissmetrics/KISSmetrics-Android-SDK#13]
```Java
java.util.ConcurrentModificationException
       at java.util.HashMap$HashIterator.nextEntry(HashMap.java:806)
       at java.util.HashMap$KeyIterator.next(HashMap.java:833)
       at com.kissmetrics.sdk.QueryEncoder.encodeProperties(QueryEncoder.java:142)
       at com.kissmetrics.sdk.QueryEncoder.createEventQuery(QueryEncoder.java:207)
       at com.kissmetrics.sdk.ArchiverImpl.archiveEvent(ArchiverImpl.java:539)
       at com.kissmetrics.sdk.TrackingRunnablesTrackingState$4.run(TrackingRunnablesTrackingState.java:113)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)
```
version: KISSmetricsSDKKv2.0.5

**Comment by healyk** [comment]
Closing as a wontfix.
