### ISSUE TITLE
NullPointer

### ISSUE THREAD

**Issue by MrAndreatta** [kissmetrics/KISSmetrics-Android-SDK#15]
```
0java.lang.NullPointerException
1	at libcore.net.http.HttpEngine.readResponse(HttpEngine.java:818)
2	at libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:283)
3	at libcore.net.http.HttpURLConnectionImpl.getHeaderFields(HttpURLConnectionImpl.java:158)
4	at libcore.net.http.HttpsURLConnectionImpl.getHeaderFields(HttpsURLConnectionImpl.java:231)
5	at com.splunk.mint.network.http.MonitorableHttpsURLConnection.disconnect(MonitorableHttpsURLConnection.java:57)
6	at com.kissmetrics.sdk.ConnectionImpl.sendRecord(ConnectionImpl.java:98)
7	at com.kissmetrics.sdk.SenderReadyState.sendTopRecord(SenderReadyState.java:36)
8	at com.kissmetrics.sdk.SenderReadyState.access$0(SenderReadyState.java:31)
9	at com.kissmetrics.sdk.SenderReadyState$1.run(SenderReadyState.java:54)
10	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
11	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
12	at java.lang.Thread.run(Thread.java:856)
```

**Comment by healyk** [comment]
No steps to reproduce provided.  Closing.
